---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

# Install Visual Studio Code

We download the .deb package from [Running VS Code on Linux](https://code.visualstudio.com/docs/setup/linux) (the exact file link is [Visual Studio Code .deb package (64-bit)](https://go.microsoft.com/fwlink/?LinkID=760868)). We run below from console.

```{bash}
sudo dpkg -i <file>.deb
sudo apt-get install -f # Install dependencies
```

If you see an error when deleting files from the VS Code Explorer on the Debian operating system, it might be because the trash implementation that VS Code is using is not there.

Run these commands to solve this issue:

```{bash}
sudo apt-get install gvfs-bin
```

## Node.js

We also install node.js package manager as per guidance from [Installing Node.js via package manager](https://nodejs.org/en/download/package-manager/)

```{bash}
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
# install build tools
sudo apt-get install -y build-essential
```

## .NET Core

We find prerequisites for .NET Core on Linux in [Prerequisites for .NET Core on Linux](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x). We install it following guidance on [Install .NET Core SDK on Linux Ubuntu 16.04](https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current).

```{bash}
wget -q packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
# Update the products available for installation, then install the .NET SDK.
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1.200
```

## Extensions (optional)

We install a few extensions.

* [C#](https://code.visualstudio.com/docs/languages/csharp)
* [Python](https://code.visualstudio.com/docs/languages/python)
* [C/C++](https://code.visualstudio.com/docs/languages/cpp)
* [Java Extension Pack](https://code.visualstudio.com/docs/languages/java)
* [Docker](https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker)
* [Azure IoT Toolkit](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit)
* [Azure IoT Edge](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-edge)
* [Azure Functions for Visual Studio Code](https://code.visualstudio.com/tutorials/functions-extension/getting-started)
* [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner)
* [MySQL Management Tools](https://marketplace.visualstudio.com/items?itemName=formulahendry.vscode-mysql)
* [Docker Explorer](https://marketplace.visualstudio.com/items?itemName=formulahendry.docker-explorer)
* [Azure Storage Explorer](https://marketplace.visualstudio.com/items?itemName=formulahendry.azure-storage-explorer)

Note that C# development requires Node.js and NPM installs.

## Using .NET Core in Visual Studio Code

* [Using .NET Core in Visual Studio Code](https://code.visualstudio.com/docs/other/dotnet)

# .Net Core on Raspberry

* [MSDN: Setting up Raspian and .NET Core 2.0 on a Raspberry Pi](https://blogs.msdn.microsoft.com/david/2017/07/20/setting_up_raspian_and_dotnet_core_2_0_on_a_raspberry_pi/)

* [Github: .NET Core on Raspberry Pi](https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md)

* [alexellis: Build .NET Core apps for Raspberry Pi with Docker](https://blog.alexellis.io/dotnetcore-on-raspberrypi/)

* [Michael Dimoudis: IoT in .NET with a Raspberry Pi, Azure IoT Hub, and Xamarin](https://medium.com/@dimoss/iot-in-net-with-a-raspberry-pi-azure-iot-hub-and-xamarin-3bf1cfb2514f)

SSH into Pi

* [StackExchange: How to achieve multiple independent sessions into a Raspbian Pi3](https://raspberrypi.stackexchange.com/questions/68464/how-to-achieve-multiple-independent-sessions-into-a-raspbian-pi3)

```{bash}
ssh pi@192.168.178.38
```

Check if latest firmware is applied.

```{bash}
sudo apt-get install rpi-update && echo Y | sudo rpi-update
```

Install .Net Core on the RPi.

```{bash}
# Install the packages necessary for .NET Core
sudo apt-get -y install libunwind8 gettext

# Download the nightly binaries for .NET Core 2
wget https://dotnetcli.blob.core.windows.net/dotnet/Runtime/release/2.0.0/dotnet-runtime-latest-linux-arm.tar.gz

# Create a folder to hold the .NET Core 2 installation
sudo mkdir /opt/dotnet

# Unzip the dotnet zip into the dotnet installation folder
sudo tar -xvf dotnet-runtime-latest-linux-arm.tar.gz -C /opt/dotnet

# set up a symbolic link to a directory on the path so we can call dotnet
sudo ln -s /opt/dotnet/dotnet /usr/local/bin
```

Install wiringpi.

```{bash}
sudo apt-get install wiringpi
```

In order to set system locale (in case not already done - usually leads to console errors such as `perl: warning: Setting locale failed.`), go to the Raspberry Pi config and update locale and timezone settings. Once all done, then sudo reboot.

```{bash}
sudo raspi-config
sudo reboot
```

Test the .Net Core installation.

```{bash}
dotnet --info
```

On your development machine, install the Raspberry Pi C# template.

```{bash}
dotnet new -i RaspberryPi.Template::*
```

This will create a new template available to dotnet core – you can list them all with a new template called `Empty .NET Core IoT Project`.

```{bash}
dotnet new --list
```

Create a new console application using this template.

```{bash}
dotnet new coreiot -n HelloRaspbian
```

## Install Cake

* [Cake Docs: Getting Started](https://cakebuild.net/docs/tutorials/getting-started)

Before installing Cake, install [Mono](http://www.mono-project.com/) which will be required for builds on Linux.

```{bash}
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
sudo apt install apt-transport-https
echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
sudo apt update
sudo apt install mono-devel -y
# check install
mono --version
```

We get cake install files.

```{bash}
curl -Lsfo build.sh https://cakebuild.net/download/bootstrapper/linux
```

The project director should now look something like below (note that project was opened in VS Code and dependencies installed by VS Code upon opening prompt)

```
[HelloRaspbian]$ ls -al
total 88
drwxrwxr-x 4 triamus triamus 4096 Mai 13 22:21 .
drwxrwxr-x 4 triamus triamus 4096 Mai 13 22:20 ..
drwxrwxr-x 3 triamus triamus 4096 Mai 13 22:20 bin
-rw-rw-r-- 1 triamus triamus  623 Mai 13 01:40 build.cake
-rwxrwxr-x 1 triamus triamus 3210 Mai 13 00:49 build.sh
-rw-rw-r-- 1 triamus triamus  264 Mai 13 00:32 HelloRaspbian.csproj
-rw-rw-r-- 1 triamus triamus  212 Mai 13 00:32 NuGet.config
drwxrwxr-x 3 triamus triamus 4096 Mai 13 22:21 obj
-rw-rw-r-- 1 triamus triamus  208 Mai 13 00:32 Program.cs
-rw-rw-r-- 1 triamus triamus  386 Mai 13 00:32 README.txt
```

Now, open the `build.cake` file and you’ll see some defaults at the top of the file. Adjust where necessary (keep all other lines untouched). The directory has already been created on the RPi via `mkdir -p /home/pi/DotNetConsoleApps/RaspbianTest`. The adjusted part looks as follows.

```
///////////////////////////////////////////////////////////////////////
// ARGUMENTS (WITH DEFAULT PARAMETERS FOR LINUX (Ubuntu 16.04, Raspbian Jessie, etc)
///////////////////////////////////////////////////////////////////////
var runtime = Argument("runtime", "linux-arm");
var destinationIp = Argument("destinationPi", "192.168.178.38");
var destinationDirectory = Argument("destinationDirectory", @"/home/pi/DotNetConsoleApps/RaspbianTest");
var username = Argument("username", "pi");
//var sessionname = Argument("sessionname", "<<your-saved-putty-sessionname>");
var executableName = Argument("executableName", "HelloRaspbian");
```

Deploy this application to your Pi running Raspbian using Cake. The script will detect that you don't have Cake and automatically download it from NuGet.

```{bash}
chmod +x ./build.sh
./build.sh
```

To test the deployment execute below from the RPi.

```{bash}
./DotNetConsoleApps/RaspbianTest/HelloRaspbian
```

https://github.com/jeremylindsayni/RaspberryPi.Cake.Template/blob/master/build.cake

https://github.com/michaeldimoudis/raspberrypi-xamarin-iot/blob/master/rpi/build.cake



